name: Build wheels

on:
  pull_request:
  release:
    types: [created, edited]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows isn't working right now: https://github.com/caketop/python-starlark-go/issues/4
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        if: runner.os != 'Linux'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1.2.0

      - name: Build sdist
        if: runner.os == 'Linux'
        run: |
          python setup.py sdist

      - name: Build Linux wheels
        if: runner.os == 'Linux'
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BEFORE_ALL: 'sh ./scripts/install-go.sh'
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS: x86_64 i686 aarch64

      - name: Build macOS wheels
        if: runner.os == 'macOS'
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_ARCHS: x86_64 universal2

      - name: Build Windows wheels
        if: runner.os == 'Windows'
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-*
          CIBW_SKIP: cp37-*

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./wheelhouse/*.whl
            ./dist/*.tar.gz

      # - name: Publish sdist
      #   if: runner.os == 'Linux'
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     twine check ./dist/*.tar.gz
      #     twine upload --skip-existing ./dist/*


      # - name: Publish wheels
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     twine check ./wheelhouse/*.whl
      #     twine upload --skip-existing ./wheelhouse/*
