name: Build wheels

on:
  pull_request:
  release:
    types: [created, edited]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1.2.0

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y
          choco install golang -f -y
          choco install mingw -f -y

      - uses: actions/setup-go@v2
        if: runner.os == 'macOS'

      - name: Install dependencies
        run: python -m pip install --upgrade -r development.txt

      - name: Build sdist
        if: runner.os == 'Linux'
        run: |
          python setup.py sdist

      - name: Build Linux wheels
        if: runner.os == 'Linux'
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BEFORE_ALL: 'pwd && ls && chmod +x ./scripts/setup-universal.sh && ./scripts/setup-universal.sh'
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*

      - name: Build macOS wheels
        if: runner.os == 'macOS'
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*

      - name: Build Windows wheels
        if: runner.os == 'Windows'
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./wheelhouse/*.whl
            ./dist/*.tar.gz

      # - name: Publish sdist
      #   if: runner.os == 'Linux'
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     twine check ./dist/*.tar.gz
      #     twine upload --skip-existing ./dist/*


      # - name: Publish wheels
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     twine check ./wheelhouse/*.whl
      #     twine upload --skip-existing ./wheelhouse/*
