name: Test

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        experimental: [false]
        include:
          - python-version: '3.13-dev'
            # sets continue-on-error automatically
            experimental: true

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip wheel
            python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: |
          export PYTHONFAULTHANDLER=1
          tox
